### ISSUE TITLE
Cannot update WebResource suddenly

### ISSUE THREAD

**Issue by SpiffyM** [MscrmTools/MsCrmTools.WebResourcesManager#22]
![image](https://cloud.githubusercontent.com/assets/26377489/23847709/a48ce60c-080e-11e7-9a27-26eb70739efb.png)

I was using til last week and it's fine. Just try to use it on Monday after system reboot and showing the error when updating the edited webresource. Creating and publishing new webresource is fine.

************** Exception Text **************
System.Exception: Error while updating web resource: 'WebResource' entity doesn't contain attribute with Name = 'dsta_name'.
   at MsCrmTools.WebResourcesManager.AppCode.WebResourceManager.UpdateWebResource(WebResource wr)
   at MsCrmTools.WebResourcesManager.WebResourcesManager.<UpdateWebResources>b__23_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

dsta_ is ther prefix of my org and it has nothing to do with WebResource entity but it suddenly shows up and couldn't update the files anymore.

**Comment by MscrmTools** [comment]
is dsta_name is the name of the webresource itself?

**Comment by MscrmTools** [comment]
No answer, closing the issue
