### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by larsey** [MscrmTools/MsCrmTools.WebResourcesManager#31]
Since replacing with file does not work I copy&pasted code from Visual Studio. When I then try to save (by clicking on the save menu item and also CTRL+S) I get an error:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.WebResourcesManager.WebResourcesManager.InnerSave(IWebResourceControl control)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

----------------------------------------
XrmToolBox
    Assembly Version: 1.2017.7.18
    Win32 Version: 1.2017.7.18

**Comment by MscrmTools** [comment]
what is the version of WebResourceManager?

**Comment by MscrmTools** [comment]
No news, closing this issue. 

Please reopen it if it still occurs
