### ISSUE TITLE
Unable to retrieve the root folder (loading local web resources)

### ISSUE THREAD

**Issue by awesomegithubusername** [MscrmTools/MsCrmTools.WebResourcesManager#55]
Hello;

After the latest update (1.2018.7.26), I can no longer load web resources from a local folder. The following message appears after clicking to browse to a local folder: 

Unhandled exception has occurred in your application.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Unable to retrieve the root folder.
   at System.Windows.Forms.FolderBrowserDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at MscrmTools.WebresourcesManager.Forms.CustomFolderBrowserDialog.btnBrowse_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
***********************************************************************************

XrmToolBox  : 1.2018.7.26
WebResources Manager : 2.2018.6.3
OS: Windows 7 SP1

**Comment by MscrmTools** [comment]
I guess it occurs because the last folder used does not exist anymore. You may try to clean the LastFolderUsed settings in the WRM settings file

**Comment by awesomegithubusername** [comment]
I cleaned the "LastFolderUsed" entry. The exception isn't thrown anymore but no web resource is loaded either (It works in version 1.2018.6.25).

**Comment by MscrmTools** [comment]
Can you show the content of the folder you want to load?

**Comment by awesomegithubusername** [comment]
The folder contains only javascript files: 

![image](https://user-images.githubusercontent.com/13295503/42747975-4eeaa15e-88d6-11e8-9255-2616e4fdf3dd.png)

**Comment by MscrmTools** [comment]
ok, thanks for these information. I will review the code

**Comment by MscrmTools** [comment]
ok, found the bug. Fix on its way
